api:
  dashboard: true
  insecure: true
  
entryPoints:
  web:
    address: ":80"

ping:
  entryPoint: web

log:
  level: DEBUG

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true  
